name: LongerDays
main: com.lith.longerdays.Plugin

version: 0.0.5
api-version: 1.20

description: A MineCraft plugin for Longer Days
author: Lith
website: https://github.com/ImLith/mc-longer-days

depend: [LithCore]
softdepend: []
